config/routes.rb
Rails.application.routes.draw do
  get 'balance/index'
  get 'transfer/index'
  get 'transfer/sender_type'
  get 'transfer/sender_name'
  get 'transfer/beneficiary_type'
  get 'transfer/beneficiary_name'
  post 'transfer/submit'
  get 'home/index'
  
  resources :groups
  resources :users, controller: 'groups', type: 'User'
  resources :teams, controller: 'groups', type: 'Team'
  resources :stocks, controller: 'groups', type: 'Stock'

  root 'home#index'
end

app/models/application_record.rb
class AddNewRecord < ActiveRecord::Migration
  def change
    add_column :groups, :wallet_id, :integer
  end
end

app/models/group.rb
class Group < ActiveRecord::Base 
    belongs_to :wallet
    self.inheritance_column = :type

    scope :user, -> { where(type: 'User') }
	  scope :team, -> { where(type: 'Team') }
	  scope :stock, -> { where(type: 'Stock') }

  class << self
    def types
      %w(User Team Stock)
    end
  end

end

app/models/stock.rb
class Stock < Group; end

app/models/team.rb
class Team < Group; end

app/models/user.rb
class User < Group; end

app/models/wallet.rb
class Wallet < ActiveRecord::Base 
  has_many :groups
  delegate :user, :team, :stock, to: :groups
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/balance_controller.rb
class BalanceController < ApplicationController
  def index
    @wallets = Group.all
    @users = Group.where(type: "User")
    @teams = Group.where(type: "Team")
    @stocks = Group.where(type: "Stock")
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/transfer_controller.rb
class TransferController < ApplicationController

  def index
    @users = Group.where(type: "User")
    @teams = Group.where(type: "Team")
  end

  def sender_type
    if params[:type].present?
      @users = Group.where(type: params[:type])
    end
    if request.xhr?
      respond_to do |format|
        format.json {
          render json: @users
        }
      end
    end
  end

  def sender_name
    if params[:id].present?
      @user = Group.where(id: params[:id])
    end
    if request.xhr?
      respond_to do |format|
        format.json {
          render json: @user
        }
      end
    end
  end

  def beneficiary_type
    if params[:type].present?
      @teams = Group.where(type: params[:type])
    end
    if request.xhr?
      respond_to do |format|
        format.json {
          render json: @teams
        }
      end
    end
  end

  def beneficiary_name
    if params[:id].present?
      @user = Group.where(id: params[:id])
    end
    if request.xhr?
      respond_to do |format|
        format.json {
          render json: @user
        }
      end
    end
  end

  def submit
    if request.xhr?

      # find by id
      sender = Group.find_by_id(params[:sender])
      beneficiary = Group.find_by_id(params[:beneficiary])

      # doing the calculation
      sender_balance = sender['balance'].to_f - params[:amount].to_f
      beneficiary_balance = beneficiary['balance'].to_f + params[:amount].to_f

      if sender['balance'].to_f > params[:amount].to_f and sender['id'] != beneficiary['id']
        # update the balance
        sender.update_attributes!(:balance => sender_balance)
        beneficiary.update_attributes!(:balance => beneficiary_balance)

        respond_to do |format|
          format.json {
            render json: {status: 1, sender: sender_balance, beneficiary: beneficiary_balance}
          }
        end
      else
        respond_to do |format|
          format.json {
            render json: {status: 0, message: 'Insufficient Balance. Or Beneficiary name are the same as Sender.'}
          }
        end
      end

    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/balance_helper.rb
module BalanceHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/transfer_helper.rb
module TransferHelper
end

app/views/balance/index.html.erb
<div class="container content">
  <div class="row">
    <div class="col-md-12">
      <h1>Balance</h1>
      <p class="mb-5">List of all existing balance.</p>
      <div class="row mt-5">
        <div class="col-md-4">
          <h3>Users</h3>
          <p>Find all balance by user name.</p>
          <ul class="list-group">
          <% @users.each do |row| %>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              <%= row.name %>
              <span class="badge badge-primary badge-pill">$ <%= row.balance %></span>
            </li>
          <% end %>
          </ul>
        </div>
        <div class="col-md-4">
          <h3>Teams</h3>
          <p>Find all balance by team name.</p>
          <ul class="list-group">
          <% @teams.each do |row| %>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              <%= row.name %>
              <span class="badge badge-primary badge-pill">$ <%= row.balance %></span>
            </li>
          <% end %>
          </ul>
        </div>
        <div class="col-md-4">
          <h3>Stocks</h3>
          <p>Find all balance by stock ID.</p>
          <ul class="list-group">
          <% @stocks.each do |row| %>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              <%= row.name %>
              <span class="badge badge-primary badge-pill">$ <%= row.balance %></span>
            </li>
          <% end %>
          </ul>
        </div>
      </div>
      
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Want to Start Transfer Money?</h1>
    <p>Our system will help you transfers cash to any bank accounts all over the world.<br>With no hassle and any cost.</p>
    <br>
    <p>
      <%= button_to 'Transfer Now', transfer_index_path, :method => :get,  :class => "btn btn-primary btn-lg"%>
    </p>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-lg-6">
      <h3>Title #1</h3>
      <p>Paragraph</p>
    </div>
    <div class="col-lg-6">
      <h3>Title #2</h3>
      <p>Paragraph Paragraph</p>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-dark navbar-static-top navbar-expand-md">
  <div class="container">
    <button type="button" class="navbar-toggler collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"> <span class="sr-only">Toggle navigation</span>
    </button> <%= link_to "e Wallet v0.1", root_path, class: 'navbar-brand' %>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav mr-auto">
        <li class='nav-item'><%= link_to 'Home', home_index_path, class: 'nav-link' %></li>
        <li class='nav-item'><%= link_to 'Transfer', transfer_index_path, class: 'nav-link' %></li> 
        <li class='nav-item'><%= link_to 'Balance', balance_index_path, class: 'nav-link' %></li> 
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Wallet Application" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Wallet Application" %>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/transfer/index.html.erb
<div class="container content">
  <div class="row">
    <div class="col-md-12">
      <h1>Money Transfer</h1>
      <p class="mb-5">Transfer from an account to another account.</p>
      <form id="transfer_form">
        <div class="row">
          <div class="col-md-5">
            <div class="form-group">
              <label>Sender Type</label>
              <%= select_tag "sender_type", raw("<option selected>User</option><option>Team</option><option>Stock</option>"), class: 'form-control' %>
            </div>
            <div class="form-group">
              <label>Sender Name</label>
              <%= select_tag "sender_name", options_from_collection_for_select(@users, "id", "name"), class: 'form-control' %>
            </div>
            <div class="form-group">
              <label>Balance (USD)</label>
              <input type="text" id="sender_balance" name="sender_balance" disabled class="form-control-plaintext" value="0">
            </div>
          </div>
          <div class="col-md-2">
            <div class="form-group">
              <label>Amount</label>
              <input id="amount" name="amount" type="number" class="form-control">
            </div>
            <div class="form-group">
              <button type="button" class="btn btn-primary btn-lg btn-block" id="submit">SEND</button>
            </div>
          </div>
          <div class="col-md-5">
            <div class="form-group">
              <label>Beneficiary Type</label>
              <%= select_tag "beneficiary_type", raw("<option>User</option><option selected>Team</option><option>Stock</option>"), class: 'form-control' %>
            </div>
            <div class="form-group">
              <label>Beneficiary Name</label>
              <%= select_tag "beneficiary_name", options_from_collection_for_select(@teams, "id", "name"), class: 'form-control' %>
            </div>
            <div class="form-group">
              <label>Balance (USD)</label>
              <input type="text" id="beneficiary_balance" name="beneficiary_balance" disabled class="form-control-plaintext" value="0">
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

<script>
  // when Sender Type selected
  $('#sender_type').on('change', function(){
    const type = $(this).val();
    $.ajax({
      url: "/transfer/sender_type",
      method: "GET",  
      dataType: "json",
      data: {type: type},
      error: function (xhr, status, error) {
        console.error('AJAX Error: ' + status + error);
      },
      success: function (response) {
        const users = response;
        $("#sender_name").empty();
        for(let i=0; i< users.length; i++){
          $("#sender_name").append('<option value="' + users[i]["id"] + '">' + users[i]["name"] + '</option>');
        }
        $("#sender_balance").val(users[0]["balance"]);
      }
    });
  });

  // when Sender Name selected
  $('#sender_name').on('change', function(){
    const id = $(this).val();
    $.ajax({
      url: "/transfer/sender_name",
      method: "GET",  
      dataType: "json",
      data: {id: id},
      error: function (xhr, status, error) {
        console.error('AJAX Error: ' + status + error);
      },
      success: function (response) {
        $("#sender_balance").val(response[0]['balance']);
      }
    });
  });

  // when Beneficiary Type selected
  $('#beneficiary_type').on('change', function(){
    const type = $(this).val();
    $.ajax({
      url: "/transfer/beneficiary_type",
      method: "GET",  
      dataType: "json",
      data: {type: type},
      error: function (xhr, status, error) {
        console.error('AJAX Error: ' + status + error);
      },
      success: function (response) {
        const users = response;
        $("#beneficiary_name").empty();
        for(let i=0; i< users.length; i++){
          $("#beneficiary_name").append('<option value="' + users[i]["id"] + '">' + users[i]["name"] + '</option>');
        }
        $("#beneficiary_balance").val(users[0]["balance"]);
      }
    });
  });

  // when Beneficiary Name selected
  $('#beneficiary_name').on('change', function(){
    const id = $(this).val();
    $.ajax({
      url: "/transfer/beneficiary_name",
      method: "GET",  
      dataType: "json",
      data: {id: id},
      error: function (xhr, status, error) {
        console.error('AJAX Error: ' + status + error);
      },
      success: function (response) {
        $("#beneficiary_balance").val(response[0]['balance']);
      }
    });
  });

  // submit the form
  $('#submit').on('click', function(){
      const sender = $("#sender_name").val();
      const beneficiary = $("#beneficiary_name").val();
      const amount = $("#amount").val();
      $.ajax({
        type: "POST",
        url: "/transfer/submit",
        data: { sender: sender, beneficiary: beneficiary, amount: amount },
        dataType: "json",
        success: function(response) {
          if (response['status'] === 1) {
            $("#sender_balance").val(response['sender']);
            $("#beneficiary_balance").val(response['beneficiary']);
          } else {
            alert(response['message']);
          }
          
        },
        error: function() {
          alert('error handling here');
        }
      });
  });

</script>